# This is a basic workflow to help you get started with Actions
name: CI Test

on:
#  push:
#   branches: 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      prefix:
        required: true
      count: 
        required: true
        
env:
  check: ${{ secrets.SERVER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    environment: DEV

    steps:
      - name: Run a one-line script
        run: |
            echo "folder=hey" >> $GITHUB_ENV
      - name: Run one-line script
        run: |
            for ($i = 1; $i -le ${{ github.event.inputs.count }}; $i++) { 
              echo "${{ env.folder }}"
            }
