# This is a basic workflow to help you get started with Actions
name: CI Test

on:
#  push:
#   branches: 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      prefix:
        required: true
      count: 
        required: true
        
env:
  check: ${{ secrets.SERVER }}
  
jobs:
  build:
    runs-on: windows-latest
    environment: DEV
    env:
      action_state: "hell is a good place"

    steps:
    - name: Set the value
      id: folder_path
      run: |
          "${{ env.action_state }}".Split(" ") | ForEach {
            "$_ is a token"
          }
