# This is a basic workflow to help you get started with Actions
name: CI Test

on:
#  push:
#   branches: 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      prefix:
        required: true
      count: 
        required: true
        
env:
  check: ${{ secrets.SERVER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    environment: DEV
    env:
      action_state: "hell"

    steps:
    - name: Set the value
      id: folder path
      run: |
          for ($i = 1; $i -le ${{ env.count }}; $i++){
            Set-Variable -Name "desc" -Value "${{ secrets['FOLDER$i'] }}"
            echo $desc
          }
