# This is a basic workflow to help you get started with Actions

name: CI Test

on:
#  push:
#   branches: 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      prefix:
        required: true
      count: 
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Run a one-line script
        run: |
            for ($i = 0; $i -lt ${{ github.event.inputs.count }}; $i++) { 
              echo "${{ github.event.inputs.prefix }}$i\"
            }
