name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      Environments:
        description: Add a comma before your input & input should be in single quotes
        required: false
        
env:
  env_arr: DEV

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build project
      run: echo "Compiling..."
  prepare-artifacts:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Prepare artifacts
      run: echo "Zipping..."
  build-matrix:
    needs: prepare-artifacts
    runs-on: windows-latest
    steps:
      - id: set-matrix
        run: |
            IFS=',' read -r -a arr <<<"${{ inputs.Environments }}"
            echo "::set-output name=environments_arr::$arr"
    outputs:
      environments_arr: ${{ steps.set-matrix.outputs.environments_arr }}
  deployment:
    needs: build-matrix
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.environments_arr) }}
    environment: ${{ matrix.version }}
    env: 
      greet: ${{ secrets.GREET }}
      server: ${{ secrets.SERVER_NAME }}
    runs-on: windows-latest
    steps:
    - if: ${{ env.server == 'a01' }}
      run: echo "${{ env.greet }} Superb!!"    
    - name: Executing
      run: echo "Running in $env:server server"
