name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      Environments:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build project
      run: echo "Compiling..."
  prepare-artifacts:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Prepare artifacts
      run: echo "Zipping..."
#  build-matrix:
#    needs: prepare-artifacts
#    runs-on: windows-latest
#    steps:
#      - id: set-matrix
#        run: echo '::set-output name=environments_arr::${{ github.event.inputs.Environment }}'
#    outputs:
#      environments_arr: ${{ steps.set-matrix.outputs.environments_arr }}
  deployment:
    needs: prepare-artifacts
    runs-on: windows-latest
    steps: 
    - name: Unzipping artifacts
      run: echo "Extracting files..."
    - name: First
      run: echo 'Running in "$(echo '${{ inputs.environments }}' | cut -d "," -f1)" environment'
    - name: Second
      run: echo 'Running in "$(echo '${{ inputs.environments }}' | cut -d "," -f2)" environment'
 #   - name: checkout
 #     uses: actions/checkout@v2
 #   - name: Deployment in all Environments
 #     uses: ./.github/workflows/reusable-workflow.yml@master
 #     with: 
 #       environments: ${{ github.event.inputs.Environments }}
