name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      Environment:
        required: true

jobs:
  build-matrix:
    runs-on: windows-latest
    steps:
      - id: set-matrix
        run: echo '::set-output name=environments_arr::${{ github.event.inputs.Environment }}'
    outputs:
      environments_arr: ${{ steps.set-matrix.outputs.environments_arr }}
  build:
    needs: build-matrix
    strategy:
      matrix: 
        environ: ${{ fromJson(needs.build-matrix.outputs.environments_arr) }}
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      run: echo "Running ${{ github.job }} in ${{ matrix.environ }}"
