name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      Environment:
        required: true

jobs:
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      run: echo "Running in ${{ github.event.inputs.Environment }}"