name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      Environments:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build project
      run: echo "Compiling..."
  prepare-artifacts:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Prepare artifacts
      run: echo "Zipping..."
  build-matrix:
    needs: prepare-artifacts
    runs-on: windows-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=environments_arr::${{ github.event.inputs.Environments }}"
    outputs:
      environments_arr: ${{ steps.set-matrix.outputs.environments_arr }}
  deployment:
    needs: build-matrix
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.environments_arr) }}
    environment: ${{ matrix.version }}
    steps:
    - name: Executing
      run: echo "Running in {{ secrets.SERVER_NAME }} server"
