name: Learning Github Actions

on: 
  push:
  
  workflow_dispatch:
    inputs:
      Environments:
        description: Add a comma before your input & input should be in single quotes
        default: "['DEV']"
        required: false
        
env:
  environs_arr: ${{ github.event.inputs.Environments }} 
#

jobs:
  build-matrix:
    runs-on: windows-latest
    steps:
    - id: set-matrix
      if: ${{ env.environs_arr != null }}
      run: echo "name=environments_arr::${{ env.environs_arr }}" >> $GITHUB_OUTPUT
    - id: set-matrix-fail 
      if: ${{ env.environs_arr == null }}
      run: echo "hello"
    outputs:
      environments_arr: ${{ steps.set-matrix.outputs.environments_arr }}
  deployment:
    needs: build-matrix
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.environments_arr) }}
    environment: ${{ matrix.version }}
    env: 
      greet: ${{ secrets.GREET }}
      server: ${{ secrets.SERVER_NAME }}
    runs-on: windows-latest
    steps:
    - if: ${{ env.server == 'a01' }}
      run: echo "${{ env.greet }} Superb!!"    
    - name: Executing
      run: echo "Running in $env:server server"
