name: Reusable workflow 

on:
  workflow_call:
    inputs:
      environments:
        required: true
        type: string

jobs:
  example_job:
    if: inputs.environments != ''
    name: Pass input to my-action
    runs-on: windows-latest
    steps:
    - id: set-env
      run: echo 'Running in $(echo '${{ inputs.environments }}' | cut -d "," -f1) environment'
    - name: Call next
      run: echo "Calling next"
      # with input -> $(echo '${{ inputs.environments }}' | cut -d "," -f2-)
