name: Splitting a string

on: 
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
    inputs:
      str:
        required: true
        
env: 
  str: ${{ github.event.inputs.str || 'hi,hey' }}
  #check
  
jobs: 
  build:
    runs-on: windows-latest
  
    steps:
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Print branch
      run: echo ${{ steps.extract_branch.outputs.branch }}
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::$(echo '${{ env.str }}' | cut -d',' -f1)"
