name: Splitting a string

on: 
  workflow_dispatch:
    inputs:
      str:
        required: true
#${{ github.event.inputs.str }}
jobs: 
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::$(echo '${{ github.event.inputs.str }}' | cut -d',' -f1)"
    - name: Print first
      run: echo "${{ steps.splitString.outputs.A }}"
