name: Splitting a string

on: 
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
    inputs:
      str:
        required: true
        

  #check
  
jobs: 
  build:
    runs-on: windows-latest
    environment: DEV
    env: 
      str: ${{ github.event.inputs.str || secrets.GREET }}
  
    steps:
    - name: Print branch
      run: echo "${{ env.str }}"
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::$(echo '${{ env.str }}' | cut -d',' -f1)"
