name: Splitting a string

on: 
  workflow_dispatch:
    inputs:
      str:
        required: true

jobs: 
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::'$(awk -F, '{print $1}' <<< '${{ github.event.inputs.str }}')'"
    - name: Print first
      run: echo "${{ steps.splitString.outputs.A }}"
