name: Splitting a string

on: 
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
    inputs:
      str:
        required: true
        
env: 
  str: ${{ github.event.inputs.str || 'hi,hey' }}
  #check
  
jobs: 
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::$(echo '${{ env.str }}' | cut -d',' -f1)"
    - name: Print first
      run: echo "${{GITHUB_REF}}"
