name: Learning Github Actions

on: 
  workflow_dispatch:
    inputs:
      str:
        required: true

jobs:
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::${{ github.event.inputs.Environment }} | cut -d',' -f1"
    - name: Print first
      run: echo "${{ steps.splitString.outputs.A }}"
