name: test workflow dispatch

on: 
  workflow_dispatch:
    inputs:
      str:
        required: true
        
env:
  str: ${{ github.event.inputs.str || 'dev,hy' }}
#${{ github.event.inputs.str }}
jobs: 
  build:
    runs-on: windows-latest
  
    steps: 
    - name: Single line script
      id: splitString
      run: echo "::set-output name=A::$(echo '${{ env.str }}' | cut -d',' -f1)"
    - name: Print first
      run: echo "${{ steps.splitString.outputs.A }}"
