# This is a basic workflow to help you get started with Actions
name: CI Test

on:
  push:
   branches: 'feature/hello'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get the branch name
        id: get_branch
        run: |
            $branch = "${{ github.ref_name }}".replace("/", "_")
            echo "::set-output name=branchName::$branch"
            
      - name: Use the branch name
        run: echo "${{ steps.get_branch.outputs.branchName }}"
